# Generated by Django 3.0.7 on 2020-07-31 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MOVIE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.IntegerField()),
                ('A', models.FloatField()),
                ('B', models.FloatField()),
                ('C', models.FloatField()),
                ('D', models.FloatField()),
                ('E', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('A', models.FloatField()),
                ('B', models.FloatField()),
                ('C', models.FloatField()),
                ('D', models.FloatField()),
                ('E', models.FloatField()),
            ],
        ),
    ]
